version: '2.1'
services:
  zookeeper:
    image: zookeeper:3.4.13
    ports:
      - "2181:2181"
    mem_limit: 512m
    healthcheck:
      test: ["CMD-SHELL", "zkServer.sh", "status"]
      interval: 1s
      timeout: 5s
      retries: 180
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9091,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9091,EXTERNAL://${KAFKA_ADVERTISED_HOST_NAME:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CREATE_TOPICS: "my.document.chunks:1:1"
    depends_on:
      zookeeper:
        condition: service_healthy
    mem_limit: 1g
    healthcheck:
      test: ["CMD", "bash", "-c", "unset" , "JMX_PORT" ,";" ,"kafka-topics.sh","--zookeeper","zookeeper:2181","--list"]
      interval: 1s
      timeout: 5s
      retries: 180